
package edu.pge_gis.ctp.rc.gis_ws_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GISWS", targetNamespace = "http://sc.ctp.pge_gis.edu/")
public interface GISWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "describefeaturetype", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Describefeaturetype")
    @ResponseWrapper(localName = "describefeaturetypeResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.DescribefeaturetypeResponse")
    public String describefeaturetype(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcapabilities", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Getcapabilities")
    @ResponseWrapper(localName = "getcapabilitiesResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetcapabilitiesResponse")
    public String getcapabilities(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getfeature", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Getfeature")
    @ResponseWrapper(localName = "getfeatureResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetfeatureResponse")
    public String getfeature(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getfeatureinfo", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Getfeatureinfo")
    @ResponseWrapper(localName = "getfeatureinfoResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetfeatureinfoResponse")
    public String getfeatureinfo(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getgmlobject", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Getgmlobject")
    @ResponseWrapper(localName = "getgmlobjectResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetgmlobjectResponse")
    public String getgmlobject(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getmap", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Getmap")
    @ResponseWrapper(localName = "getmapResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetmapResponse")
    public byte[] getmap(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lockfeature", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Lockfeature")
    @ResponseWrapper(localName = "lockfeatureResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.LockfeatureResponse")
    public String lockfeature(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transaction", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Transaction")
    @ResponseWrapper(localName = "transactionResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.TransactionResponse")
    public String transaction(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

}
