
package edu.pge_gis.ctp.rc.gis_ws_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GISWS", targetNamespace = "http://sc.ctp.pge_gis.edu/")
public interface GISWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "describeFeatureType", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.DescribeFeatureType")
    @ResponseWrapper(localName = "describeFeatureTypeResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.DescribeFeatureTypeResponse")
    public String describefeaturetype(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCapabilities", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetCapabilities")
    @ResponseWrapper(localName = "getCapabilitiesResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetCapabilitiesResponse")
    public String getcapabilities(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFeature", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetFeature")
    @ResponseWrapper(localName = "getFeatureResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetFeatureResponse")
    public String getfeature(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFeatureInfo", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetFeatureInfo")
    @ResponseWrapper(localName = "getFeatureInfoResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetFeatureInfoResponse")
    public String getfeatureinfo(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGmlObject", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetGmlObject")
    @ResponseWrapper(localName = "getGmlObjectResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetGmlObjectResponse")
    public String getgmlobject(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMap", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetMap")
    @ResponseWrapper(localName = "getMapResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.GetMapResponse")
    public byte[] getmap(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lockFeature", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.LockFeature")
    @ResponseWrapper(localName = "lockFeatureResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.LockFeatureResponse")
    public String lockfeature(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transaction", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.Transaction")
    @ResponseWrapper(localName = "transactionResponse", targetNamespace = "http://sc.ctp.pge_gis.edu/", className = "edu.pge_gis.ctp.rc.gis_ws_client.TransactionResponse")
    public String transaction(
        @WebParam(name = "arg0", targetNamespace = "")
        GisParams arg0);

}
