
package edu.pge_gis.ctp.rc.gis_ws_client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "GISWSwmsYwfsService", targetNamespace = "http://sc.ctp.pge_gis.edu/", wsdlLocation = "http://localhost:8080/GISWSwmsYwfs/GISWSwmsYwfs?wsdl")
public class GISWSwmsYwfsService
    extends Service
{

    private final static URL GISWSWMSYWFSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/GISWSwmsYwfs/GISWSwmsYwfs?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        GISWSWMSYWFSSERVICE_WSDL_LOCATION = url;
    }

    public GISWSwmsYwfsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GISWSwmsYwfsService() {
        super(GISWSWMSYWFSSERVICE_WSDL_LOCATION, new QName("http://sc.ctp.pge_gis.edu/", "GISWSwmsYwfsService"));
    }

    /**
     * 
     * @return
     *     returns GISWS
     */
    @WebEndpoint(name = "GISWSPort")
    public GISWS getGISWSPort() {
        return (GISWS)super.getPort(new QName("http://sc.ctp.pge_gis.edu/", "GISWSPort"), GISWS.class);
    }

}
