
package edu.pge_gis.pge_service.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSProveedor", targetNamespace = "http://proveedor.pge_service.pge_gis.edu/")
public interface WSProveedor {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://proveedor.pge_service.pge_gis.edu/", className = "edu.pge_gis.pge_service.ws.client.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://proveedor.pge_service.pge_gis.edu/", className = "edu.pge_gis.pge_service.ws.client.SumarResponse")
    public int sumar(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
